### ISSUE TITLE
Console client directly accessing the silo impacts security and scalability

### ISSUE THREAD

**Issue by llebj** [llebj/orleans-on-containers#4]
#### Description

Currently the console client application connects directly to the orleans silo. There are a number of issues with this architecture:

1. Connections between orleans clients and silos are unsecure.
2. A postgresql database is currently being used as a clustering provider. Providing direct database access to all connected clients is a significant security concern. The number of clients is also limited to the maximum number of concurrent connections that the database supports, limiting scalability.

#### Proposal

Introducing frontend web servers that sit between the silo backend and the console clients has the potential to greatly improve the security and scalablility of the system. A web API can be used to ensure that only authenticated users can join a chat, while a separate web server dedicated to handling SignalR connections will ensure that persistent web socket connections do not impact the performance of the web API. These two web servers will protect both the silo server and the database from unsecure direct access. Using web servers also greatly increases the number of supported client connections before database connection limits become an issue.

#### Tasks
 - [ ] Create a web API that allows user registration and authentication.
 - [ ] Add API endpoints for interacting with chat rooms.
 - [ ] Create a web app for handling SignalR functionality.
